FROM ubuntu:latest

# Install Node.js
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# # Install node pre-requisites
# RUN apt-get update && apt-get install -y python
RUN apt-get update && \
    apt-get install -y build-essential

# Install Chromium
RUN  apt-get update \
     # See https://crbug.com/795759
     && apt-get install -yq libgconf-2-4 \
     # Install latest chrome dev package, which installs the necessary libs to
     # make the bundled version of Chromium that Puppeteer installs work.
     && apt-get install -y wget xvfb --no-install-recommends \
     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
     && apt-get update \
     && apt-get install -y google-chrome-stable --no-install-recommends \
     && rm -rf /var/lib/apt/lists/*

# Install yarn using npm
RUN npm i -g yarn

WORKDIR /app

COPY . .

RUN ls

RUN rm -rf node_modules

RUN yarn install

RUN which chromium-browser

# RUN yarn test:chrome

RUN service snapd start
RUN snap install chromium

RUN yarn run:chrome aut:ci 

# RUN yarn lint